### PR TITLE
Fix time conversion for year

### PR DESCRIPTION
**Pull request by arkodg**
* 365 days in a year, not 356

### CODE REVIEW

**Comment by arkodg** [comment]
cc @collin-lee

**Comment by collin-lee** [comment]
FYI @stefansedich

**Review by collin-lee — APPROVED** [review]

**Comment by stefansedich** [comment]
> FYI @stefansedich

I am embarrased to say I did not spot this one at all...

**Comment by zirain** [comment]
what abou leap years?

**Pull request merged**
