### PR TITLE
Add redis cluster support

### PR DESCRIPTION
**Pull request by erdody**

### CODE REVIEW

**Comment by mattklein123** [comment]
At a high level this LGTM, though will need docs in the README. @ysawa0 do you mind taking a look?

**Comment by erdody** [comment]
Thanks @mattklein123, I thought draft PRs were not visible, but it's great you could take a look anyway. 
We were planning to add documentation and an integration test before submitting the PR. 
Please let us know if you prefer a different way to configure the different redis types.

**Comment by mattklein123** [comment]
Nope this LGTM. docs/integration tests sounds great! Thank you!

**Comment by erdody** [comment]
Forgot to squash and merge the integration test. Closing in favor of a cleaner version https://github.com/envoyproxy/ratelimit/pull/179

**Comment by ysawa0** [comment]
> At a high level this LGTM, though will need docs in the README. @ysawa0 do you mind taking a look?

@mattklein123 Hi, sorry missed this. I can take a look!

**Pull request closed without merging**
