### PR TITLE
Add detailed metrics

### PR DESCRIPTION
**Pull request by jdamata**
This was partially implemented in https://github.com/envoyproxy/ratelimit/pull/242

Pretty much tried to massage the missing parts from this PR https://github.com/envoyproxy/ratelimit/pull/237 into main.

### CODE REVIEW

**Comment by bkthomps** [comment]
@jdamata I am interested in this functionality. Is this PR ready to be reviewed or are more changes required?

**Comment by jdamata** [comment]
I think this is ready for review, was using the ratelimit with this PR for a few weeks in a load testing environment and it was working without issues. 

I think some of the checks were failing because of linting but otherwise good to go

**Comment by bkthomps** [comment]
Ok sounds good thanks. @jdamata just to confirm, when the flag is enabled, stats are created as if the config had each value in it for each value matched?

**Comment by bkthomps** [comment]
Like lets say the config has
descriptors:
  key: user
  rate_limit: ...

And user a and b both match, then the stats will be domain.user.a.total_hits and domain.user.b.total_hits, etc ?

**Comment by jdamata** [comment]
Yep exactly

**Comment by bkthomps** [comment]
@mattklein123 @ysawa0 could one of you take a look at this PR please?

**Comment by mattklein123** [comment]
Please merge main and make sure CI is passing, thanks!

**Comment by bkthomps** [comment]
@jdamata could you rebase from master please so the build checks pass? Thanks.

**Comment by bkthomps** [comment]
@jdamata you might need to force push with "Signed-off-by: Joel Damata <joel.damata@pointclickcare.com>" as the commit message since the last commit didn't have it making the DCO check fail.

**Comment by bkthomps** [comment]
@jdamata Just wanted to follow up on this. Could you force push to get DCO to pass? You'll have to also make the PR be from your feature branch to main, as right now it's the opposite. Thanks.

**Comment by medalliaerlich** [comment]
hey any news on this?

**Comment by bkthomps** [comment]
@jdamata looks good! Could check that failing test? I think it's formatting issues. Thanks.

**Comment by bkthomps** [comment]
@jdamata ?

**Comment by junhuang-pin** [comment]
Hi, is there any update on this?

**Comment by bkthomps** [comment]
@jdamata Thanks for updating this. Looks to be a very in-demand PR. Could you fix the DCO check? You'll have to force push with "Signed-off-by: Joel Damata <joel.damata@pointclickcare.com>" as the commit message. Thanks.

**Comment by bkthomps** [comment]
@jdamata DCO seems to still be failing. I believe the commit not signed off for DCO is this one: "[Merge branch 'main' into main](https://github.com/envoyproxy/ratelimit/pull/323/commits/d897f0630128bc38869c6312d61ad8958c89223f)"

**Comment by bkthomps** [comment]
@jdamata hi, don't know if you saw but there's a failing test: `ratelimit_test.go:207`

**Comment by hardik42** [comment]
@jdamata Is there an update on the failing test? Thank you!

**Comment by cathoderay** [comment]
Hi, @jdamata! Can you, please, give us an estimate on when this can be merged, so we can plan accordingly? We're depending on this to move forward with our project. Appreciate it!

**Comment by bkthomps** [comment]
@jdamata sorry to bother you, but many people are looking forward to your addition.

If you are not able to work on it, I can help if you want?

**Comment by jdamata** [comment]
> @jdamata sorry to bother you, but many people are looking forward to your addition.
> 
> If you are not able to work on it, I can help if you want?

No worries! Sorry yah I've been busy with work lately. I'd appreciate the help if you got the time. 

I don't care for the git commit credit so if you want to branch out, close this pr and open a new one by all means go for it!

**Comment by bkthomps** [comment]
Ok sounds good, I'll do that. Just to confirm, you said this is working when you tested it for your purposes right?

**Comment by jdamata** [comment]
> Ok sounds good, I'll do that. Just to confirm, you said this is working when you tested it for your purposes right?

Yep, I had built my own docker image from this branch and had it working in a performance environment. Didn't notice any issues. Was able to get Prometheus to display metrics for header values and grafana graphs. I think that's what people are after

**Comment by mattklein123** [comment]
I will close this out and someone can open a new PR.

**Pull request closed without merging**
