### PR TITLE
Reduce short living tasks produced by memcached implementation and move them to goroutines pool

### PR DESCRIPTION
**Pull request by storozhukBM**
During investigation on https://github.com/envoyproxy/ratelimit/issues/250 I made a quick look at pprof results didn't show any noticeable hot spots in the `github.com/envoyproxy/ratelimit` or `github.com/bradfitz/gomemcache`
but a lot of samples were in runtime.schedule, runtime.findrunnable, runtime.futex. So I decided to reduce the potential load on the scheduler by moving the continuous spawn of new short-lived goroutines to a pool that can automatically expand to a necessary size, stabilize and stop creating new goroutines if the load remains stable.

This simple change reduced overall CPU consumption on 32 cores machine by 20% in the same setup that is described in the issue https://github.com/envoyproxy/ratelimit/issues/250

### CODE REVIEW

**Review by mattklein123 — DISMISSED** [review]
Makes sense, thanks!

**Comment by mattklein123** [comment]
Oops looks like a real CI issue, please take a look.

/wait

**Comment by mattklein123** [comment]
I would be fine with bumping the Go version, please go for it!

/wait

**Comment by storozhukBM** [comment]
@mattklein123 I bumped Go version to 1.16, please take a look

**Comment by mattklein123** [comment]
I think there might be another fix required due to the Go update. Sorry. :(

/wait

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
