### PR TITLE
client supports handling multi descriptors

### PR DESCRIPTION
**Pull request by dzy176**
This client supports handling multi descriptors by flag `-descriptors`, e.g.
**cmd:**
go run main -domain test -descriptors name=foo,age=18 -descriptors name=bar,age=14 ,
the grpc server will return a overall response for all of descriptors.
**output:**
dial string: localhost:8081
domain: test
descriptors: [ <key=name, value=foo>  <key=age, value=18> ] [ <key=name, value=bar>  <key=age, value=14> ] 
response:
 overall_code:OK  statuses:{code:OK  current_limit:{requests_per_unit:2  unit:MINUTE}  limit_remaining:1  duration_until_reset:{seconds:6}}  statuses:{code:OK  current_limit:{requests_per_unit:2  unit:MINUTE}  duration_until_reset:{seconds:6}}

@mattklein123   cloud you please check this PR?

### CODE REVIEW

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks, this LGTM. Can you maybe document this somewhere? Perhaps in the README? Whatever you think is best? Thank you!

/wait

**Comment by dzy176** [comment]
> Thanks, this LGTM. Can you maybe document this somewhere? Perhaps in the README? Whatever you think is best? Thank you!
> 
> /wait

I update some info in README

**Comment by mattklein123** [comment]
Thanks. LGTM. Let's wait until https://github.com/envoyproxy/ratelimit/pull/213 is merged and then CI will be fixed.

/wait

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Pull request merged**
