### PR TITLE
CI: Github Actions

### LINKED ISSUE #57: Public docker image
Is there a public docker image that we can use? I checked dockerhub.com and there are many images there built by 3rd parties, but I could not find one from Lyft.

### PR DESCRIPTION
**Pull request by stevesloka**
Fixes #57 by moving from TravisCI to Github Actions. 

The GH Actions build an image for each push to the `master` branch tagged with `:master`. It builds a tagged version for releases (e.g. `v*`) and also runs tests & checks on each PR. 

**TODO**: This requires two secrets to be configures for push credentials to the docker registry named otherwise the image pushing will fail:
- DOCKER_USERNAME
- DOCKER_PASSWORD

### CODE REVIEW

**Comment by mattklein123** [comment]
Awesome! @stevesloka let me get the image repo prepped and then figure out how to load up the creds.

**Comment by mattklein123** [comment]
@stevesloka thanks this LGTM. This is awesome! I made https://hub.docker.com/repository/docker/envoyproxy/ratelimit/general and populated the username/password in the secrets for this repo. Is there anything else we want to do before we merge and monitor?

**Comment by stevesloka** [comment]
@mattklein123 nope that's all that should be required. Once this merges it should kick off a build in the `master` branch and push a new `:master` tag.

**Comment by mattklein123** [comment]
Looks like it is working! :tada: 

https://hub.docker.com/repository/docker/envoyproxy/ratelimit/general

**Pull request merged**
