### PR TITLE
Support for "Memory" backend.

### PR DESCRIPTION
**Pull request by konrad-kaminski**
This is the implementation of pure memory-based backend. It is useful in situations where we do not want to have a (heavier) memcached/redis backend, but still want to use global rate limiting functionality.

### CODE REVIEW

**Comment by ysawa0** [comment]
Hi @konrad-kaminski, this looks like it could be useful but I'm not sure how it would be used. Would memory mode be used only in the situation where there is only a single instance of ratelimit running in your infrastructure and all clients call that single instance? Otherwise the rate limits would not be shared globally.

**Comment by konrad-kaminski** [comment]
Yes, that's exactly the scenario we want to support i.e. a single instance of ratelimit would support many clients to achieve global rate limits.

**Comment by ysawa0** [comment]
I see. I understand the use case but I'm not sure if that's a design we should support as it's not exactly following best practices (Not HA and if the single ratelimit instance dies, all limits are lost). cc @mattklein123 I wonder if you have any thoughts on this?

**Comment by mattklein123** [comment]
> cc @mattklein123 I wonder if you have any thoughts on this?

Yeah I had the same thought about a single point of failure and HA. It doesn't seem like this is how this service should be deployed?

**Comment by konrad-kaminski** [comment]
I understand that use cases are limited. We mostly want to support a per-second limits, thus HA would be nice, but is not necessary.

**Comment by konrad-kaminski** [comment]
@mattklein123  , @ysawa0 What are your final thoughts? We're kind of stuck waiting for the decision.

**Comment by mattklein123** [comment]
My general feeling is this isn't something we should support since there is no possible HA solution. @ysawa0 any objection?

**Comment by ysawa0** [comment]
> My general feeling is this isn't something we should support since there is no possible HA solution. @ysawa0 any objection?

Yes, I agree with that sentiment.

**Comment by konrad-kaminski** [comment]
OK. I'm closing this PR. For those who'd like that kind of functionality, we've created a fork at https://github.com/allegro/ratelimit/.

**Pull request closed without merging**
