### PR TITLE
Docker compose example update to V3 API

### PR DESCRIPTION
**Pull request by ysawa0**
Update docker compose example to V3 API.
Add example prom statsd exporter config.

### CODE REVIEW

**Comment by mattklein123** [comment]
Thanks for fixing. Check CI?

/wait

**Comment by ysawa0** [comment]
Oof, CI being flakey due to the `duration_until_reset`. Can we rerun CI for now and hope next run passes? I don't have a solution for this right now.

**Comment by mattklein123** [comment]
I tried to rerun and it failed again, so we may need to fix the flake. :(

**Comment by ysawa0** [comment]
> I tried to rerun and it failed again, so we may need to fix the flake. :(

Okay, I'll take a look

**Comment by ysawa0** [comment]
Closing in favor of #192

**Pull request closed without merging**
